import { Geist, Geist_Mono } from "next/font/google";
import { Atkinson_Hyperlegible } from "next/font/google";
import { Inter } from "next/font/google";
import { Caveat_Brush } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] })

const caveatBrush = Caveat_Brush({
  subsets: ["latin"],
  weight: "400"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={caveatBrush.className}>
        {children}
      </body>
    </html>
  );
}
